### PR TITLE
Upgrade to Spring boot 2.2.6

### PR DESCRIPTION
**Pull request by schen1**
**What does this PR do?**
Changes applied are coming from the runtime guide, basically using the newest dependencies for Spring Boot 2.2.6.

[RHSA-2020:2252 - Security Advisory](https://access.redhat.com/errata/RHSA-2020:2252)
[Spring boot 2.2.6 runtime guide](https://access.redhat.com/documentation/en-us/red_hat_support_for_spring_boot/2.2/html/spring_boot_runtime_guide/configuring-your-application-to-use-spring-boot_spring-boot)
[Red Hat support for Spring Boot: 2.2.6 Component Details](https://access.redhat.com/articles/5099911)

**Is there a relevant Issue open for this?**
No open issue

**Who would you like to review this?**

cc: @redhat-cop/containers-approvers

### CODE REVIEW

**Comment by garethahealy** [comment]
@schen1 ; is the only reason not moving to latest SB (2.3.0.RELEASE) due to RH support?

**Comment by schen1** [comment]
> @schen1 ; is the only reason not moving to latest SB (2.3.0.RELEASE) due to RH support?

Well, one thing is definitely support. If we want to use the latest SB release, then the readme should not mention the RH Application Runtimes product and we would also need to adapt the repositories URL as RH does not serve the latest SB content.

**Comment by garethahealy** [comment]
@schen1 ; thanks for the clarification. leave it as is then.

**Pull request merged**
