### PR TITLE
adding swagger UI and a README

### LINKED ISSUE #6: Add Swagger UI Support
https://springfox.github.io/springfox/docs/current/#springfox-swagger-ui

### LINKED ISSUE #7: Add A README

### PR DESCRIPTION
**Pull request by sherl0cks**
resolves #7 
resolves #6

### CODE REVIEW

**Comment by sherl0cks** [comment]
@etsauer per my comments in chat, can we take the approach of making swagger UI the default index page and let its auto config magic discover all the endpoints instead of manually enumerating them in a list. e.g. https://github.com/rht-labs/automation-api/blob/master/src/main/java/com/rhc/automation/config/HomeController.java

**Comment by sabre1041** [comment]
@sherl0cks @etsauer I agree with the `spring-fox` approach. Makes it much more dynamic in swagger generation as features begin to get added

**Comment by etsauer** [comment]
agreed as well.

**Comment by sherl0cks** [comment]
OK will update accordingly. For some reason `redirect` is not working correctly in this app like it does in the example I shared. I'll work on finding a root cause.

**Comment by sherl0cks** [comment]
@etsauer done, for some reason `redirect:url` does not work like normal, suggesting some autoconfig magic is not quite right. I did get it to work though by being explicit with `RedirectView`

I also switched the component scan so you don't have a frustrating moment later where a controller doesn't register.

**Pull request merged**
